services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    hostname: nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    type: 'none'
    o: bind
    device: 'users/${USER}/data/wordpress'
  mariadb:
    driver: local
    type: 'none'
    o: bind
    device: 'users/${USER}/data/mariadb'
