services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    hostname: nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_pass
      - wp_admin_pass
      - wp_user_pass
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_pass
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  adminer:
    build: requirements/adminer/.
    container_name: adminer
    restart: on-failure
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      - mariadb

secrets:
  db_pass:
    file: ../secrets/db_pass.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt 
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      device: ${DATA_PATH}/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver_opts:
      device: ${DATA_PATH}/mariadb
      o: bind
      type: none
