services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_content:/var/www/html/wp-content
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wp_content:/var/www/html/wp-content
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

volumes:
  db_data:
  wp_content:

networks:
  inception:
    driver: bridge
