services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    expose:
      - "9000"