services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    hostname: nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
