services:
    nginx:
        build: requirements/nginx/.
        container_name: nginx
        restart: on-failure
        env_file:
        - .env
        ports:
        - "443:443"

    wordpress:
        build: requirements/wordpress/.
        container_name: wordpress
        depends_on:
        - mariadb
        restart: on-failure
        env_file:
        - .env
        expose:
        - "9000"
        volumes:
        # Mount wp-content for persistent uploads, themes, plugins
        - wp_content:/var/www/html/wp-content
    
    mariadb:
        build: requirements/mariadb/.
        container-name: mariadb
        restart: on-failure
        env_file:
        - .env
        expose:
        - "3306"
        volumes:
        - db_data:/var/lib/mysql

volumes:
  db_data:
  wp_content:
